<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.5o6K95C' shared service.

return $this->privates['service_locator.5o6K95C'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('manager' => function () {
    return ($this->services['doctrine.orm.default_entity_manager'] ?? $this->load(__DIR__.'/getDoctrine_Orm_DefaultEntityManagerService.php'));
}, 'transactionRepo' => function (): ?\App\Repository\TransactionRepository {
    return ($this->privates['App\Repository\TransactionRepository'] ?? $this->load(__DIR__.'/getTransactionRepositoryService.php'));
}));
