<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.TrB_07B' shared service.

return $this->privates['service_locator.TrB_07B'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('tagRepo' => function (): ?\App\Repository\TagRepository {
    return ($this->privates['App\Repository\TagRepository'] ?? $this->load(__DIR__.'/getTagRepositoryService.php'));
}));
