<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'algolia_client' shared service.

include_once $this->targetDirs[3].'/vendor/algolia/algoliasearch-client-php/src/AlgoliaSearch/Client.php';

return $this->privates['algolia_client'] = new \AlgoliaSearch\Client($this->getEnv('ALGOLIA_APP_ID'), $this->getEnv('ALGOLIA_API_KEY'));
