<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'argument_resolver.service' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/ServiceValueResolver.php';

return $this->privates['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\ServiceLocator(array('App\\Controller\\AdminController:deleteUser' => function () {
    return ($this->privates['service_locator.g4MUsbG'] ?? $this->load(__DIR__.'/getServiceLocator_G4MUsbGService.php'));
}, 'App\\Controller\\AdminController:editUser' => function () {
    return ($this->privates['service_locator.g4MUsbG'] ?? $this->load(__DIR__.'/getServiceLocator_G4MUsbGService.php'));
}, 'App\\Controller\\AdminController:index' => function () {
    return ($this->privates['service_locator.u1Jd59A'] ?? $this->load(__DIR__.'/getServiceLocator_U1Jd59AService.php'));
}, 'App\\Controller\\CustomerController:registerCustomer' => function () {
    return ($this->privates['service_locator.Qkh2rqa'] ?? $this->load(__DIR__.'/getServiceLocator_Qkh2rqaService.php'));
}, 'App\\Controller\\HomeController:index' => function () {
    return ($this->privates['service_locator.BHIn3hZ'] ?? $this->load(__DIR__.'/getServiceLocator_BHIn3hZService.php'));
}, 'App\\Controller\\ProductController:deleteProduct' => function () {
    return ($this->privates['service_locator.cwYPq6f'] ?? $this->load(__DIR__.'/getServiceLocator_CwYPq6fService.php'));
}, 'App\\Controller\\ProductController:editProduct' => function () {
    return ($this->privates['service_locator.cwYPq6f'] ?? $this->load(__DIR__.'/getServiceLocator_CwYPq6fService.php'));
}, 'App\\Controller\\ProductController:index' => function () {
    return ($this->privates['service_locator.4kt5kzb'] ?? $this->load(__DIR__.'/getServiceLocator_4kt5kzbService.php'));
}, 'App\\Controller\\SecurityController:login' => function () {
    return ($this->privates['service_locator.ltE88OR'] ?? $this->load(__DIR__.'/getServiceLocator_LtE88ORService.php'));
}, 'App\\Controller\\TagController:product' => function () {
    return ($this->privates['service_locator.Ly3VALB'] ?? $this->load(__DIR__.'/getServiceLocator_Ly3VALBService.php'));
}, 'App\\Controller\\TagController:search' => function () {
    return ($this->privates['service_locator.TrB_07B'] ?? $this->load(__DIR__.'/getServiceLocator_TrB07BService.php'));
}, 'App\\Controller\\TransactionController:add' => function () {
    return ($this->privates['service_locator.5o6K95C'] ?? $this->load(__DIR__.'/getServiceLocator_5o6K95CService.php'));
}, 'App\\Controller\\TransactionController:cart' => function () {
    return ($this->privates['service_locator.U4mjn_a'] ?? $this->load(__DIR__.'/getServiceLocator_U4mjnAService.php'));
}, 'App\\Controller\\TransactionController:deleteTransaction' => function () {
    return ($this->privates['service_locator.IGMCTmj'] ?? $this->load(__DIR__.'/getServiceLocator_IGMCTmjService.php'));
}, 'App\\Controller\\TransactionController:index' => function () {
    return ($this->privates['service_locator.U4mjn_a'] ?? $this->load(__DIR__.'/getServiceLocator_U4mjnAService.php'));
}, 'App\\Controller\\AdminController::deleteUser' => function () {
    return ($this->privates['service_locator.g4MUsbG'] ?? $this->load(__DIR__.'/getServiceLocator_G4MUsbGService.php'));
}, 'App\\Controller\\AdminController::editUser' => function () {
    return ($this->privates['service_locator.g4MUsbG'] ?? $this->load(__DIR__.'/getServiceLocator_G4MUsbGService.php'));
}, 'App\\Controller\\AdminController::index' => function () {
    return ($this->privates['service_locator.u1Jd59A'] ?? $this->load(__DIR__.'/getServiceLocator_U1Jd59AService.php'));
}, 'App\\Controller\\CustomerController::registerCustomer' => function () {
    return ($this->privates['service_locator.Qkh2rqa'] ?? $this->load(__DIR__.'/getServiceLocator_Qkh2rqaService.php'));
}, 'App\\Controller\\HomeController::index' => function () {
    return ($this->privates['service_locator.BHIn3hZ'] ?? $this->load(__DIR__.'/getServiceLocator_BHIn3hZService.php'));
}, 'App\\Controller\\ProductController::deleteProduct' => function () {
    return ($this->privates['service_locator.cwYPq6f'] ?? $this->load(__DIR__.'/getServiceLocator_CwYPq6fService.php'));
}, 'App\\Controller\\ProductController::editProduct' => function () {
    return ($this->privates['service_locator.cwYPq6f'] ?? $this->load(__DIR__.'/getServiceLocator_CwYPq6fService.php'));
}, 'App\\Controller\\ProductController::index' => function () {
    return ($this->privates['service_locator.4kt5kzb'] ?? $this->load(__DIR__.'/getServiceLocator_4kt5kzbService.php'));
}, 'App\\Controller\\SecurityController::login' => function () {
    return ($this->privates['service_locator.ltE88OR'] ?? $this->load(__DIR__.'/getServiceLocator_LtE88ORService.php'));
}, 'App\\Controller\\TagController::product' => function () {
    return ($this->privates['service_locator.Ly3VALB'] ?? $this->load(__DIR__.'/getServiceLocator_Ly3VALBService.php'));
}, 'App\\Controller\\TagController::search' => function () {
    return ($this->privates['service_locator.TrB_07B'] ?? $this->load(__DIR__.'/getServiceLocator_TrB07BService.php'));
}, 'App\\Controller\\TransactionController::add' => function () {
    return ($this->privates['service_locator.5o6K95C'] ?? $this->load(__DIR__.'/getServiceLocator_5o6K95CService.php'));
}, 'App\\Controller\\TransactionController::cart' => function () {
    return ($this->privates['service_locator.U4mjn_a'] ?? $this->load(__DIR__.'/getServiceLocator_U4mjnAService.php'));
}, 'App\\Controller\\TransactionController::deleteTransaction' => function () {
    return ($this->privates['service_locator.IGMCTmj'] ?? $this->load(__DIR__.'/getServiceLocator_IGMCTmjService.php'));
}, 'App\\Controller\\TransactionController::index' => function () {
    return ($this->privates['service_locator.U4mjn_a'] ?? $this->load(__DIR__.'/getServiceLocator_U4mjnAService.php'));
})));
