<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVkpO71D\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVkpO71D/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerVkpO71D.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerVkpO71D\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerVkpO71D\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'VkpO71D',
    'container.build_id' => '6a634aa1',
    'container.build_time' => 1523526231,
));
