<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8yxWn7i\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8yxWn7i/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container8yxWn7i.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\Container8yxWn7i\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \Container8yxWn7i\srcDevDebugProjectContainer(array(
    'container.build_hash' => '8yxWn7i',
    'container.build_id' => '9adeac59',
    'container.build_time' => 1524570544,
));
