<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIYiLdAv\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIYiLdAv/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerIYiLdAv.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerIYiLdAv\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerIYiLdAv\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'IYiLdAv',
    'container.build_id' => '980d4ef4',
    'container.build_time' => 1523457917,
));
