<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.Ly3VALB' shared service.

return $this->privates['service_locator.Ly3VALB'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('productRepo' => function (): ?\App\Repository\ProductRepository {
    return ($this->privates['App\Repository\ProductRepository'] ?? $this->load(__DIR__.'/getProductRepositoryService.php'));
}));
